import { useState, useCallback } from "react";
import { FileCode, Upload, Download, Copy, Check, ChevronDown, AlertCircle, Cpu } from "lucide-react";
import { useLanguage } from "@/i18n/LanguageContext";
import { useMachines } from "@/hooks/useMachines";

// ─── Controller types ────────────────────────────────────────────────
type ControllerType = "heidenhain" | "siemens" | "fanuc" | "okuma" | "mazak";

interface ControllerDef {
  id: ControllerType;
  label: string;
  dialect: string;
  ext: string;
}

const CONTROLLERS: ControllerDef[] = [
  { id: "heidenhain", label: "Heidenhain (TNC / iTNC)", dialect: "Heidenhain Dialog", ext: "H" },
  { id: "siemens",    label: "Siemens (840D / 828D)",   dialect: "DIN/ISO Siemens",   ext: "MPF" },
  { id: "fanuc",      label: "Fanuc (30i / 31i)",       dialect: "Fanuc G-Code",      ext: "NC" },
  { id: "okuma",      label: "Okuma (OSP-P300)",        dialect: "Okuma G-Code",      ext: "MIN" },
  { id: "mazak",      label: "Mazak (Mazatrol ISO)",    dialect: "Mazak ISO G-Code",  ext: "EIA" },
];

// ─── CLS token types ─────────────────────────────────────────────────
interface ClsToken {
  type: string;
  raw: string;
  args: string[];
}

function parseCLS(text: string): ClsToken[] {
  const tokens: ClsToken[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("$$")) continue;
    const match = line.match(/^([A-Z_/]+)\s*[/,]?\s*(.*)/);
    if (!match) continue;
    const [, type, rest] = match;
    const args = rest.split(/[/,\s]+/).filter(Boolean);
    tokens.push({ type, raw: line, args });
  }
  return tokens;
}

// ─── Converter core ──────────────────────────────────────────────────
function convertCLS(tokens: ClsToken[], ctrl: ControllerType, programName: string): string {
  const lines: string[] = [];
  let toolId = "";
  let spindleSpeed = 0;
  let feedRate = 0;
  let coolantOn = false;
  let x = 0, y = 0, z = 0;

  const n = (i: number) => String(i).padStart(3, "0");
  let seq = 10;
  const nl = () => seq += 10;

  // ─ header ─
  if (ctrl === "heidenhain") {
    lines.push(`BEGIN PGM ${programName.toUpperCase()} MM`);
  } else if (ctrl === "siemens") {
    lines.push(`; ${programName.toUpperCase()}.MPF`);
    lines.push("; Generated by GAGE Post Processor");
    lines.push("G17 G90 G94");
  } else {
    lines.push(`%`);
    lines.push(`O${programName.replace(/\D/g, "").padStart(4, "1").slice(0, 4)}`);
    lines.push("(Generated by GAGE Post Processor)");
    lines.push("G17 G21 G90 G94");
  }

  for (const tok of tokens) {
    switch (tok.type) {
      case "PPRINT": {
        const msg = tok.args.join(" ");
        if (ctrl === "heidenhain") lines.push(`; ${msg}`);
        else lines.push(`(${msg})`);
        break;
      }

      case "PARTNO":
      case "MACHIN": {
        const msg = `${tok.type}: ${tok.args.join(" ")}`;
        if (ctrl === "heidenhain") lines.push(`; ${msg}`);
        else lines.push(`(${msg})`);
        break;
      }

      case "CUTTER": {
        const dia = parseFloat(tok.args[0] || "10");
        if (ctrl === "heidenhain") {
          lines.push(`; CUTTER DIA = ${dia} mm`);
        } else {
          lines.push(`(CUTTER DIA = ${dia})`);
        }
        break;
      }

      case "LOADTL": {
        toolId = tok.args[0] || "1";
        const tNum = parseInt(toolId, 10);
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} TOOL CALL ${tNum} Z`);
          nl();
        } else if (ctrl === "siemens") {
          lines.push(`T${tNum} D1`);
          lines.push(`M06`);
        } else {
          lines.push(`N${seq} T${tNum} M06`);
          nl();
        }
        break;
      }

      case "SPINDL": {
        const rpm = parseFloat(tok.args[0] || "1000");
        spindleSpeed = rpm;
        const dir = tok.args.find(a => a === "CLW" || a === "CCLW");
        if (ctrl === "heidenhain") {
          const m = dir === "CCLW" ? "M4" : "M3";
          lines.push(`N${n(seq)} S${rpm} ${m}`);
          nl();
        } else if (ctrl === "siemens") {
          const m = dir === "CCLW" ? "M4" : "M3";
          lines.push(`S${rpm} ${m}`);
        } else {
          const m = dir === "CCLW" ? "M04" : "M03";
          lines.push(`N${seq} S${rpm} ${m}`);
          nl();
        }
        break;
      }

      case "FEDRAT": {
        feedRate = parseFloat(tok.args[0] || feedRate.toString());
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} F${feedRate}`);
          nl();
        } else if (ctrl === "siemens") {
          lines.push(`F${feedRate}`);
        } else {
          // fanuc/okuma/mazak: F is inline, skip standalone
        }
        break;
      }

      case "RAPID": {
        if (ctrl === "heidenhain") {
          lines.push(`; RAPID ON`);
        } else {
          lines.push(ctrl === "siemens" ? `G00` : `N${seq} G00`);
          nl();
        }
        break;
      }

      case "GOTO": {
        const px = parseFloat(tok.args[0] ?? "0");
        const py = parseFloat(tok.args[1] ?? "0");
        const pz = parseFloat(tok.args[2] ?? "0");
        x = px; y = py; z = pz;
        const xs = px.toFixed(3), ys = py.toFixed(3), zs = pz.toFixed(3);
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} L X${xs} Y${ys} Z${zs} FMAX`);
          nl();
        } else if (ctrl === "siemens") {
          lines.push(`G00 X${xs} Y${ys} Z${zs}`);
        } else {
          lines.push(`N${seq} G00 X${xs} Y${ys} Z${zs}`);
          nl();
        }
        break;
      }

      case "GODLTA": {
        const dx = parseFloat(tok.args[0] ?? "0");
        const dy = parseFloat(tok.args[1] ?? "0");
        const dz = parseFloat(tok.args[2] ?? "0");
        x += dx; y += dy; z += dz;
        const xs = x.toFixed(3), ys = y.toFixed(3), zs = z.toFixed(3);
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} L X${xs} Y${ys} Z${zs} F${feedRate}`);
          nl();
        } else if (ctrl === "siemens") {
          lines.push(`G91 G01 X${dx.toFixed(3)} Y${dy.toFixed(3)} Z${dz.toFixed(3)} F${feedRate}`);
          lines.push(`G90`);
        } else {
          lines.push(`N${seq} G91 G01 X${dx.toFixed(3)} Y${dy.toFixed(3)} Z${dz.toFixed(3)} F${feedRate}`);
          nl();
          lines.push(`N${seq} G90`);
          nl();
        }
        break;
      }

      case "CIRCLE": {
        // CIRCLE / cx,cy,cz,dx,dy,dz,ang
        const cx = parseFloat(tok.args[0] ?? "0");
        const cy = parseFloat(tok.args[1] ?? "0");
        const cz = parseFloat(tok.args[2] ?? "0");
        const ir = (cx - x).toFixed(3);
        const jr = (cy - y).toFixed(3);
        const kr = (cz - z).toFixed(3);
        const endX = parseFloat(tok.args[3] ?? x.toString()).toFixed(3);
        const endY = parseFloat(tok.args[4] ?? y.toString()).toFixed(3);
        const endZ = parseFloat(tok.args[5] ?? z.toString()).toFixed(3);
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} CC X${cx.toFixed(3)} Y${cy.toFixed(3)}`);
          nl();
          lines.push(`N${n(seq)} C X${endX} Y${endY} Z${endZ} DR+ F${feedRate}`);
          nl();
        } else {
          const g = ctrl === "siemens" ? "" : `N${seq} `;
          lines.push(`${g}G03 X${endX} Y${endY} Z${endZ} I${ir} J${jr} K${kr} F${feedRate}`);
          nl();
        }
        break;
      }

      case "COOLNT": {
        const on = tok.args[0]?.toUpperCase() !== "OFF";
        coolantOn = on;
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} ${on ? "M08" : "M09"}`);
          nl();
        } else if (ctrl === "siemens") {
          lines.push(on ? "M08" : "M09");
        } else {
          lines.push(`N${seq} ${on ? "M08" : "M09"}`);
          nl();
        }
        break;
      }

      case "END": {
        if (ctrl === "heidenhain") {
          lines.push(`N${n(seq)} M30`);
          nl();
          lines.push(`END PGM ${programName.toUpperCase()} MM`);
        } else if (ctrl === "siemens") {
          lines.push("M30");
        } else {
          lines.push(`N${seq} M30`);
          nl();
          lines.push("%");
        }
        break;
      }

      default: {
        if (ctrl === "heidenhain") lines.push(`; ${tok.raw}`);
        else lines.push(`(${tok.raw})`);
      }
    }
  }

  // safety footer if END was missing
  if (!tokens.find(t => t.type === "END")) {
    if (ctrl === "heidenhain") lines.push(`N${n(seq)} M30\nEND PGM ${programName.toUpperCase()} MM`);
    else if (ctrl === "siemens") lines.push("M30");
    else { lines.push(`N${seq} M30`); lines.push("%"); }
  }

  return lines.join("\n");
}

// ─── Sample CLS ──────────────────────────────────────────────────────
const SAMPLE_CLS = `$$ NX Post Processor - CLS Sample
PARTNO / ORNEK_PARCA
MACHIN / MACHINING_CENTER, 1
PPRINT / GAGE Toolroom Post Processor Test
CUTTER / 16.0
LOADTL / 1, OSETNO, 1
SPINDL / 8000, RPM, CLW
RAPID
GOTO / 0.000, 0.000, 50.000
FEDRAT / 800, MMPM
GOTO / 100.000, 50.000, 5.000
GOTO / 100.000, 50.000, -5.000
GODLTA / 50.000, 0.000, 0.000
GODLTA / 0.000, 30.000, 0.000
COOLNT / ON
GOTO / 0.000, 0.000, 50.000
COOLNT / OFF
END`;

// ─── Component ───────────────────────────────────────────────────────
const PostProcessor = () => {
  const { t } = useLanguage();
  const { machines } = useMachines();

  const [clsInput, setClsInput] = useState(SAMPLE_CLS);
  const [controller, setController] = useState<ControllerType>("heidenhain");
  const [selectedMachineId, setSelectedMachineId] = useState<string>("");
  const [programName, setProgramName] = useState("PROGRAM_01");
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [converted, setConverted] = useState(false);

  const selectedCtrl = CONTROLLERS.find(c => c.id === controller)!;

  const handleConvert = useCallback(() => {
    setError("");
    try {
      const tokens = parseCLS(clsInput);
      if (!tokens.length) throw new Error("CLS verisi boş veya okunamadı.");
      const result = convertCLS(tokens, controller, programName);
      setOutput(result);
      setConverted(true);
    } catch (e: unknown) {
      setError((e as Error).message);
    }
  }, [clsInput, controller, programName]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      setClsInput(ev.target?.result as string);
      setConverted(false);
      setOutput("");
      setProgramName(file.name.replace(/\.[^.]+$/, "").toUpperCase().replace(/\s+/g, "_").slice(0, 16));
    };
    reader.readAsText(file);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${programName}.${selectedCtrl.ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="industrial-card p-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-primary/20">
            <Cpu className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">CLS Post Processor</h2>
            <p className="text-xs text-muted-foreground">NX / APT CLS → Makine G-Kodu</p>
          </div>
        </div>
        {converted && (
          <div className="flex gap-2">
            <button onClick={handleCopy} className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-secondary hover:bg-secondary/80 transition-colors text-sm">
              {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
              {copied ? "Kopyalandı" : "Kopyala"}
            </button>
            <button onClick={handleDownload} className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-secondary hover:bg-secondary/80 transition-colors text-sm">
              <Download className="w-4 h-4" />
              .{selectedCtrl.ext}
            </button>
            <button onClick={() => handleDownload("tap")} className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-primary text-primary-foreground hover:brightness-110 transition-all text-sm">
              <Download className="w-4 h-4" />
              .TAP
            </button>
          </div>
        )}
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* LEFT — Settings + CLS Input */}
        <div className="space-y-4">

          {/* Controller selection */}
          <div>
            <label className="label-industrial block mb-2">CNC Kontrolcü</label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {CONTROLLERS.map(c => (
                <button
                  key={c.id}
                  onClick={() => setController(c.id)}
                  className={`text-left px-3 py-2 rounded-lg border text-sm transition-all ${
                    controller === c.id
                      ? "border-primary bg-primary/10 text-foreground"
                      : "border-border bg-card hover:border-primary/50 text-muted-foreground"
                  }`}
                >
                  <span className="font-medium block">{c.label}</span>
                  <span className="text-xs opacity-70">{c.dialect} · .{c.ext}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Machine select */}
          {machines.length > 0 && (
            <div>
              <label className="label-industrial block mb-2">Tezgah (opsiyonel)</label>
              <select
                value={selectedMachineId}
                onChange={e => setSelectedMachineId(e.target.value)}
                className="input-industrial w-full"
              >
                <option value="">— Seçiniz —</option>
                {machines.map(m => (
                  <option key={m.id} value={m.id}>{m.label} ({m.brand} {m.model})</option>
                ))}
              </select>
            </div>
          )}

          {/* Program name */}
          <div>
            <label className="label-industrial block mb-2">Program Adı</label>
            <input
              type="text"
              value={programName}
              onChange={e => setProgramName(e.target.value.toUpperCase().replace(/\s+/g, "_").slice(0, 20))}
              className="input-industrial w-full font-mono"
              maxLength={20}
              placeholder="PROGRAM_01"
            />
          </div>

          {/* CLS Input */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="label-industrial">CLS / APT Girişi</label>
              <label className="flex items-center gap-1.5 cursor-pointer text-xs text-primary hover:text-primary/80 transition-colors">
                <Upload className="w-3.5 h-3.5" />
                Dosya Yükle
                <input type="file" accept=".cls,.apt,.clt,.ncf,.txt" onChange={handleFileUpload} className="hidden" />
              </label>
            </div>
            <textarea
              value={clsInput}
              onChange={e => { setClsInput(e.target.value); setConverted(false); setOutput(""); }}
              className="input-industrial w-full font-mono text-xs resize-none"
              rows={18}
              placeholder="CLS verisini buraya yapıştırın..."
              spellCheck={false}
            />
          </div>

          {/* Convert button */}
          <button
            onClick={handleConvert}
            className="w-full py-2.5 rounded-lg bg-primary text-primary-foreground font-semibold hover:brightness-110 transition-all flex items-center justify-center gap-2"
          >
            <FileCode className="w-4 h-4" />
            Çevir → {selectedCtrl.label}
          </button>

          {error && (
            <div className="flex items-start gap-2 p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-destructive text-sm">
              <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
              {error}
            </div>
          )}
        </div>

        {/* RIGHT — G-Code Output */}
        <div className="flex flex-col">
        <div className="bg-card rounded-lg border border-border overflow-hidden flex-1 flex flex-col">
            <div className="flex items-center justify-between px-4 py-2 bg-secondary/30 border-b border-border">
              <div className="flex items-center gap-2">
                <FileCode className="w-3.5 h-3.5 text-muted-foreground" />
                <span className="text-xs text-muted-foreground font-mono">
                  {programName}.{selectedCtrl.ext}
                </span>
              </div>
              <span className={`text-xs font-mono ${converted ? "text-success" : "text-muted-foreground"}`}>
                {converted ? `● ${selectedCtrl.dialect}` : "● Bekleniyor"}
              </span>
            </div>
            <pre className="p-4 text-xs font-mono text-success overflow-auto flex-1 whitespace-pre min-h-[400px]">
              {output || (
                <span className="text-muted-foreground">
                  {`// Çıktı burada görünecek\n// Soldaki panelden CLS verinizi\n// girin ve "Çevir" butonuna tıklayın.`}
                </span>
              )}
            </pre>
          </div>

          {/* Stats */}
          {converted && (
            <div className="grid grid-cols-3 gap-2 mt-3">
              <div className="p-2 rounded-lg bg-card border border-border text-center">
                <div className="text-lg font-mono text-primary">{output.split("\n").length}</div>
                <div className="text-xs text-muted-foreground">Satır</div>
              </div>
              <div className="p-2 rounded-lg bg-card border border-border text-center">
                <div className="text-lg font-mono text-accent">{parseCLS(clsInput).length}</div>
                <div className="text-xs text-muted-foreground">CLS Token</div>
              </div>
              <div className="p-2 rounded-lg bg-card border border-border text-center">
                <div className="text-lg font-mono text-success">{Math.round(output.length / 1024 * 10) / 10}K</div>
                <div className="text-xs text-muted-foreground">Boyut</div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PostProcessor;
